# Generated by Django 4.2.7 on 2023-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='кличка')),
                ('breed', models.CharField(max_length=100, verbose_name='порода')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='порода')),
                ('birthday', models.DateField(verbose_name='дата рождения')),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'собаки',
            },
        ),
    ]
